### ISSUE TITLE
Parent Uri incorrect 

### ISSUE THREAD

**Issue by anupash** [indigo-dc/cdmi-s3-qos#1]
curl -X GET http://localhost:8080/cdmi_capabilities/container/Profile1 -H "Authorization: Basic cmVzdGFkbWluOnJlc3RhZG1pbg==" -H "Content-Type: application/cdmi-capability"

{
  "metadata": {
    "cdmi_data_redundancy": "1",
    "cdmi_latency": "1000",
    "cdmi_geographic_placement": "[\"DE\",\"FR\"]"
  },
  "capabilities": {
    "cdmi_data_redundancy": "true",
    "cdmi_latency": "true",
    "cdmi_geographic_placement": "true",
    "cdmi_capabilities_exact_inherit": "true",
    "cdmi_capabilities_templates": "true",
    "cdmi_capabilities_allowed": "/cdmi_capabilities/container/Profile2"
  },
  **"parentURI": "cdmi_capabilities/container",**
  "objectName": "Profile1",
  "objectID": "0001869F001842AF61656266633735392D383437332D3464",
  "parentID": "0001869F00183FA738313565626430342D313031392D3432",
  "objectType": "application/cdmi-capability"
}

It should be 
"parentURI": "/cdmi_capabilities/container",

**Comment by komputerowiec** [comment]
The error came from CDMI server itself.
I just tested commit 024e1b2 of INDIGO CDMI server, and it has been fixed.
